[package]
name = "moba"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.7.0", features = [ "trace"]}
bevy_rapier3d = { version = "*", features = [ "enhanced-determinism" ] }
bevy_egui = "0.13"
bevy_simple_networking = { git = "https://github.com/ggaast/bevy_simple_networking.git" , branch = "main"}
bytes = "1"
iyes_loopless = "0.3.0"
bevy_system_graph = "0.1.1"
bevy_snap = { git = "https://github.com/johanhelsing/bevy_snap", version = "0.2.0"}


priority-queue = "1.2.1"

[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
