[package]
name = "go"
version = "0.0.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "modules/*",
]


[dependencies]
bevy = { version = "0.7.0", features = [ "trace"]}
bevy_rapier3d = { git = "https://github.com/dimforge/bevy_rapier", features = [ "enhanced-determinism" ] }
bevy_egui = "0.13"
bevy_simple_networking = { git = "https://github.com/ggaast/bevy_simple_networking.git" , branch = "main"}
bytes = "1"
iyes_loopless = "0.3.0"

rapier3d = "0.12.0"
serde = "1.0.137"
serde_json = "1.0.81"

networking = { path = "modules/networking"}
core = { path = "modules/core"}
gocha = { path = "modules/gocha"}

priority-queue = "1.2.1"
