[package]
name = "Griffsort"
version = "0.0.6"
edition = "2021"
author = "Sigzaa Studio"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [ "crates/*" ]

[dependencies]
bevy = { version = "0.7.0", features = ["jpeg"]}
corgee = { path = "crates/corgee" , version = "0.1.0"}
reactive = { path = "crates/reactive" , version = "0.1.0"}
go_character = { path = "crates/go_character", version = "0.0.5"}
go_level = { path = "crates/go_level", version = "0.1.0"}
inspector = { path = "crates/inspector" }
ui = { path = "crates/ui" }
bevy_editor_pls = { git = "https://github.com/jakobhellermann/bevy_editor_pls" }
bincode = "1.3.1"
serde = "1.0.137"



