[package]
name = "inspector"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8.0"
bevy_egui = "0.15"
corgee = { path = "../corgee", version = "*" }
