[package]
name = "go_core"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.7.0", features = [ "trace"]}
serde = "1.0.137"
serde_json = "1.0.81"